### ISSUE TITLE
Доработать алгоритм

### ISSUE THREAD

**Issue by Kasiwadzaki** [Layzerg/testV3#1]
Добрый день, меня зовут Вадим, я представитель компании Uno-Soft.

На файле https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-4.txt.gz выходит ошибка по памяти при ограничении -Xmx1G.  
Прошу доработать алгоритм.

**Comment by Layzerg** [comment]
Добрый день,  Вадим!
Ошибка исправлена.
